/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/admin/AdminHeader.vue')['default']
    AdminSidebar: typeof import('./components/admin/AdminSidebar.vue')['default']
    AppAvatar: typeof import('./components/common/AppAvatar.vue')['default']
    AppButton: typeof import('./components/common/AppButton.vue')['default']
    AppConfirmDialog: typeof import('./components/common/AppConfirmDialog.vue')['default']
    AppEmpty: typeof import('./components/common/AppEmpty.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppImageUpload: typeof import('./components/common/AppImageUpload.vue')['default']
    AppInfiniteScroll: typeof import('./components/common/AppInfiniteScroll.vue')['default']
    AppLoading: typeof import('./components/common/AppLoading.vue')['default']
    AppModal: typeof import('./components/common/AppModal.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    CommentItem: typeof import('./components/content/CommentItem.vue')['default']
    CommentList: typeof import('./components/content/CommentList.vue')['default']
    ConversationItem: typeof import('./components/message/ConversationItem.vue')['default']
    ConversationList: typeof import('./components/message/ConversationList.vue')['default']
    DataTable: typeof import('./components/admin/DataTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FollowButton: typeof import('./components/user/FollowButton.vue')['default']
    ImageCarousel: typeof import('./components/content/ImageCarousel.vue')['default']
    MessageBubble: typeof import('./components/message/MessageBubble.vue')['default']
    MessageInput: typeof import('./components/message/MessageInput.vue')['default']
    MessageList: typeof import('./components/message/MessageList.vue')['default']
    MobileNav: typeof import('./components/layout/MobileNav.vue')['default']
    NoteCard: typeof import('./components/content/NoteCard.vue')['default']
    NoteDetail: typeof import('./components/content/NoteDetail.vue')['default']
    NoteForm: typeof import('./components/content/NoteForm.vue')['default']
    NoteWaterfall: typeof import('./components/content/NoteWaterfall.vue')['default']
    ReviewStatusBadge: typeof import('./components/admin/ReviewStatusBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./components/content/ShareButton.vue')['default']
    StatCard: typeof import('./components/admin/StatCard.vue')['default']
    TagList: typeof import('./components/content/TagList.vue')['default']
    TopicChip: typeof import('./components/content/TopicChip.vue')['default']
    TopicDetailDialog: typeof import('./components/content/TopicDetailDialog.vue')['default']
    UserCard: typeof import('./components/user/UserCard.vue')['default']
    UserInfo: typeof import('./components/user/UserInfo.vue')['default']
    UserStatsBar: typeof import('./components/user/UserStatsBar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
